### PR TITLE
Library update

### PR DESCRIPTION
**Pull request by iAmShorty**
update and cleanup

### CODE REVIEW

**Comment by TheSerapher** [comment]
Good idea - but we need some testing for this. No idea if our custom JS code may be affected by the update (or any of the libraries we are using that depend on jQuery).

**Comment by iAmShorty** [comment]
i have checked every page with active debugger, no errors so far. pages work fine, api and ajax calls also. will test that over the weekend, but i thinks it's ok.

**Comment by TheSerapher** [comment]
Great, feel free to merge once everything is checked.

**Comment by iAmShorty** [comment]
:+1:

**Comment by iAmShorty** [comment]
runs fine over the weekend, will merge today when you don't mind.

**Comment by TheSerapher** [comment]
No prob :)

**Pull request merged**
