### PR TITLE
Recents Bitcoin's Change (> v0.17)

### PR DESCRIPTION
**Pull request by lubuzzo**
As requested on #2761 and maybe on #2764, this PR add compatibility to the recents Bitcoin's changes.

On BTC 0.17 accounts was deprecated, instead we have labels - even as deprecated, we still could use using the “deprecatedrpc=accounts”, on the latest Bitcoin version (0.18) the support for accounts was entire removed.

And following @TheSerapher desire, I tried keep the backward compatibility with the "outdated" versions of Bitcoin. 

Also, this PR we include the coin_c11.class - for Chaincoin's based coins.

And I fixed a typo, but this is trivial.

### CODE REVIEW

**Comment by SmarterHomes** [comment]
tAck on Bitcoin 0.16-0.18rc1 codebase RPC protocol. Backwards compatibility untested. Looks like @lubuzzo has established this in a more simple way than anticipated in the original issue, please review. 
The added c11.class is actually correcting an untracked issue of difficulty bits conversion.

**Comment by r4sas** [comment]
With which RPC versions it _already_ tested?

**Comment by lubuzzo** [comment]
I tested on 0.17.

HashUnlimited is doing a test on 0.16.


Em qua, 6 de mar de 2019 19:34, R4SAS <notifications@github.com> escreveu:

**Comment by r4sas** [comment]
On backend level all seems correct with back-comp. Tested with 0.8.X based coin.

**Comment by TheSerapher** [comment]
Please keep testing extensively. I will merge once I got the approval of a few people. Other than that, this LGTM - nice work and thanks!

This will be merged and a new version will be released too.

**Comment by TheSerapher** [comment]
Sorry for being AWOL but how does this look? Should I just merge it for easy availability in master?

**Comment by SmarterHomes** [comment]
no issues here since March with 0.18 and 0.13 codebases

**Comment by JCAK1967** [comment]
> no issues here since March with 0.18 and 0.13 codebases

Works but I have the following message error on Apache Log

[Sat Apr 10 14:06:42.949576 2021] [php7:notice] [pid 13254] [client 192.168.1.66:11942] PHP Notice:  Undefined index: errors in /var/www/MPOS/templates/compile/bootstrap/c39d708de58f784acc1130ae3db2429442f76503.file.status.tpl.php on line 61, referer: http://192.168.1.115/index.php?page=account&action=earnings

Could someone let me know the fix for this error or the implications in another process ?

Thanks

**Pull request merged**
