### PR TITLE
Just a little Theme refresh :)

### PR DESCRIPTION
**Pull request by iAmShorty**
I'm getting tired of seeing the old bootstrap theme, so i decided to do a little theme refresh :laughing: 

Done
- brand new interface
- new styling on all pages
- new Dashboard
- new notifications
- switching colors when something is wrong
- switching colors in dashboard when values are out of bounds
- new graphs
- cleaned up the old bootstrap theme
- moved common used libs to globals

Todo
- some styling on Dashboard
- implementing new libs for smarter graphs
- many things i don't know at the moment
- live notifications

It's tested and works fine, just the Dashboard needs some more tweaking...

Feel free to test it and let me know if you like it and what else should be implemented or changed in that new theme.

### CODE REVIEW

**Comment by TheSerapher** [comment]
I'll try it out. Make sure it's feature complete before merging :)

**Comment by TheSerapher** [comment]
Dude .... this is great! Very good work so far.

And now that the core code is pretty much untouched adding new themes isn't a bad thing anymore. At least we are not changing templates all the time anymore ;-)

For those interested:

screen shot 2016-07-06 at 15 56 44

**Comment by TheSerapher** [comment]
Quick note, User Dropdown CSS is below information boxes:

screen shot 2016-07-06 at 15 58 21

**Comment by TheSerapher** [comment]
While you are at it and we had a ticket for this before, try using BTC as the algorithm to test with since that one uses the highest precision for decimals. I doubt we can make those fit in these boxes but at least we can give it a shot. Or we just start to display < 0.0000001 when the estimates are too low :)

Thanks for your work! Cool to see you back for something neat like this :)

**Comment by TheSerapher** [comment]
If this is the theme: https://wrapbootstrap.com/theme/blue-moon-admin-template-WB0375140

We can't use it. This comes with a multi-license that we certainly can't afford out of our pockets.

Please double check on that before we even consider merging this. Our themes have to be open source and freely available or we can't merge/use them.

**Comment by iAmShorty** [comment]
hmm, this one was free of charge two weeks ago. i will contact the author if we can use this as our frontend.

**Comment by dileep96** [comment]
Registration is not working on this. Please fix it

**Comment by iAmShorty** [comment]
can you show me the error message?

**Comment by iAmShorty** [comment]
done...

**Comment by dileep96** [comment]
untitled

This is what i get after entering details and clicking register. I rolled back to bootstrap theme and its working perfectly

**Comment by iAmShorty** [comment]
it's working. i fixed it a few minutes ago

**Comment by dileep96** [comment]
It worked. Thanks

**Comment by TheSerapher** [comment]
Any update on if we can use this theme at all?

**Comment by iAmShorty** [comment]
no response from developer using the contact form on wrapbootstrap :disappointed: 

i will try via twitter or facebook.

**Comment by TheSerapher** [comment]
Block percentages don't show on the dashboard for the last blocks found :)

**Comment by iAmShorty** [comment]
will check that this evening, i'm out of office today

**Comment by peltzermike** [comment]
Any updates on this theme?

How can I grab a copy of it?

**Comment by iAmShorty** [comment]
still no response from developer. i will stop implementing this until there is no response from him. Sorry

**Pull request closed without merging**
