### PR TITLE
Implement Read/Write Split directly on PHP / Fixed statistics->graphs page

### PR DESCRIPTION
**Pull request by tperalta82**
The statistics->graphs page was not working because smarty was escaping html chars, thus breaking javascript.

Since the mysqlnd_ms extension does not work on php7, only php5, I implemented a simple Read/Write query splitting.

Tested while monitoring both master/slave instances.

### CODE REVIEW

**Comment by TheSerapher** [comment]
Thanks for reopening the PR :-)

The MySQL change will allow MPOS to run on PHP 7? What’s the idea behind that change?

**Comment by TheSerapher** [comment]
Lerts merge this into develeopment and let people test it out.

So anyone able to give this a whirl, feel free to do so!

**Comment by tperalta82** [comment]
Thanks for the add, well i'm running it on php7.0 with no issues so far, but it works out of the box.
The only thing that was not working was the read/write splitting because the extension mentioned in the wiki has no support for PHP7, hence I made it in PHP by extending mysqli and implementing it in a way ProxySQL works, but with prepared statements , that ProxySQL doesn't support.

Am running it in a production environment for days now, no issues.
I might add some more code in the future.

Awesome project man.

**Comment by tperalta82** [comment]
Found a small bug (lack of validation) in the code, doesn't affect anything, just throws some warnings that 'll fix today

**Pull request merged**
