### PR TITLE
fix "field doesn't have a default values" error

### PR DESCRIPTION
**Pull request by r4sas**
Otherwise cron will return error: `Failed to update share statistics for %username%: SQL Query failed: 1364`

I using pool with prop payout, and always see that error. That will fix it.

### CODE REVIEW

**Comment by TheSerapher** [comment]
For this to be merged we will need to add an upgrade script for existing databases, add the new version for the DB structure and update the version file too to reflect the expected DB version. Just the base file will only help people with new setups not existing ones.

And the PR should be against development not master.

I guess you have miners without any valid shares, only invalid ones, hence the error.

**Comment by r4sas** [comment]
>upgrade script for existing databases

Will do

>And the PR should be against development not master.

Hm... It against development branch

> I guess you have miners without any valid shares, only invalid ones, hence the error.

According to [updateShareStatistics](https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L203-L208) function, you update values not in all fields, that's why we got error. Maybe here we also must fill `pplns_valid` and `pplns_invalid` fields with `$aStats['pplns_valid']` and `$aStats['pplns_invalid']`?

**Comment by TheSerapher** [comment]
My bad, mobile app doesn't show the branch. All good! I am fairly sure we dont need to fill with PPLNS data, those are already archived shares which are not required in the statistics since they were already parsed for regular payouts.

**Comment by TheSerapher** [comment]
Did you give that upgrade script a quick test run? :)

**Comment by r4sas** [comment]
Currently testing it

**Comment by r4sas** [comment]
Now should work as intended

**Comment by TheSerapher** [comment]
Thanks! I will merge into dev for people to test it.

**Pull request merged**
