### PR TITLE
Possibly fixed all the MySQL errors from my previous pull request

### PR DESCRIPTION
**Pull request by tperalta82**
Since I extended the mysqli class to implement read/write, i totally forgot to implement "a last used" connection in case of error, otherwise the errors would be bogus and totally untraceable.

Been running for days in a big pool, no issues so far

### CODE REVIEW

**Comment by TheSerapher** [comment]
Looks promising so I merge into development, maybe you can find a few users to test on their own pools as well so we have a wider acceptance of it.

**Comment by tperalta82** [comment]
Is there any official forum or somewhere I can post it? 
I'll also add the sql_mode in the future for mysql 5.7 compat without changing mysql server itself

**Comment by tperalta82** [comment]
so far i'm running it on https://hbc.multipools.club

**Comment by TheSerapher** [comment]
No official forum since it’s not really maintained anymore other than pull requests by others.

The sql mode may help indeed.

**Pull request merged**
