### PR TITLE
Don't rely on the default account on payout time, …

### PR DESCRIPTION
**Pull request by Quix0r**
… better use all accounts (found in valid).

Example:
$ ./peerunityd listaccounts
{
    "" : -128.50823600,
    "main" : 22.00000000,
    "miner" : 62.27911800,
    "mpos" : 66.41823600
}

As you can see, relying only on default account isn't what you want.

### CODE REVIEW

**Comment by TheSerapher** [comment]
This will cause error 500 on some wallets. We had tried that in the past and it messed up payouts for badly maintained wallets.

We have since then removed this and enforce the coins to stay in the default wallet for all payouts. It may be not a clean way but it's the only way to support all balance implementations across all wallets.

**Comment by Quix0r** [comment]
Here in my wallet I have -128 so it will probably never start paying out? I run mpos (successfully setup) in my LAN, not accessible from outside. It is a test-attempt to pool all my miners locally.

**Comment by TheSerapher** [comment]
You simply transfer from one account address in you local wallet to one account address of the default account in your wallet.

In you case, moving your coins to the default account will result in a positive balance of `22.189118` coins.

I know this is very annoying (we spent a LOT of time trying to get this done better), but as long as different wallets use different techniques (or run on various bugs?), this can't be any more generic than "use your default account for payouts".

**Comment by Quix0r** [comment]
Sorry for a rooky question, but how do I do so?

**Comment by TheSerapher** [comment]
Read the documentation die your Coind, most likely sendtoaddress

**Comment by Quix0r** [comment]
Or just rename the account's labels to "" (empty string). ?

**Comment by TheSerapher** [comment]
Can try but not sure that would work.

**Comment by Quix0r** [comment]
Seems to:

````
$ ~/git/peerunity/src/peerunityd listaccounts
{
    "" : 22.17000000
}
$
````

**Comment by TheSerapher** [comment]
Great! Good to know ;-)

**Pull request closed without merging**
