### PR TITLE
Update findblock.php

### PR DESCRIPTION
**Pull request by shtse8**
Fixed Invalid Blockhash by `listsinceblock`.

```
RPC call did not return 200: HTTP error: 500 - JSON Response: [-8] Invalid blockhash
```

### CODE REVIEW

**Comment by TheSerapher** [comment]
Again against development branch please. And maybe test out another few coins just to make sure they also work with this change and won’t throw an error.

**Comment by shtse8** [comment]
I am sure bitcoin family coins works on this `getblockhash` api. because it is a standard api to get the blockhash by index. If we worry it will throw an error, we can try catch and then set an empty string like previous version. Also, I am pointing to development branch already.

**Comment by shtse8** [comment]
It should be fine now.
When it throw
```
PHP Fatal error:  Uncaught Exception: RPC call did not return 200: HTTP error: 500 - JSON Response: [-8] Invalid blockhash
```
Then, set it back to empty like previous version.

**Comment by TheSerapher** [comment]
Thanks!

**Pull request merged**
