### PR TITLE
implement manual payout from API (#2634)

### PR DESCRIPTION
**Pull request by r4sas**
Implements request from #2634.
API action: manualpayout
Required arguments: `api_key`, `pin`

### CODE REVIEW

**Comment by TheSerapher** [comment]
I remember why this wasn't added ... someone could easily use this system to lock-out users by supplying a wrong PIN multiple times. PINs are only required when already logged in not for any API calls. And I am hestinant to remove it completely for the sake for this API to work without the potential to break accounts.

Thoughts?

**Comment by r4sas** [comment]
No problems

**Comment by xisi** [comment]
I feel obligated to mention that this should absolutely be put behind a config setting and opt-in; there are more than a few ways this can and likely will be abused.

**Comment by r4sas** [comment]
By the way. requiring PIN prevent untrusted admins (who not have access to DB) to execute that request against `id` specified in request.

**Comment by TheSerapher** [comment]
I think the lockout can't be removed. That would allow for easy brute-force attacks. Keep trying until the PIN works. Now the attacker has the PIN of a user. Seems not like a good idea.

In the end I don't think this is at all a good idea. It may add a benefit but it surely doesn't help in regards of security. Closing this and the opened issue.

**Pull request closed without merging**
