### PR TITLE
Implemented recaptcha v2

### PR DESCRIPTION
**Pull request by AmazingDreams**
Google will soon drop support for Recaptcha v1: #2641

I am using composer to install the google recaptcha lib.

Running in production here: https://pool.amazingsystems.nl/index.php

### CODE REVIEW

**Comment by daygle** [comment]
I think this change needs a little more work before merging.

I'll try make some time to make some improvements.

**Comment by TheSerapher** [comment]
Let me know when this is ready and I wll trigger the merge :-) And re-target against development please, then I can merge right away.

**Comment by TheSerapher** [comment]
Since composer isn't part of the installation procedure maybe add the library itself too? I doubt people would notice this is now required to run and I see people making tickets for this.

**Comment by TheSerapher** [comment]
The PR looks rather messed up. If you plan to submit recaptcha-v2 as a PR, please remove files that are unrelated to that change. Would make reverting more difficult, not to mention unrelated files makes a review pretty hard :-/

**Comment by AmazingDreams** [comment]
Yes sorry. I suppose I messed up rebasing against dev..

**Comment by TheSerapher** [comment]
No problem, let me know when it's ready for a review.

**Comment by AmazingDreams** [comment]
I've just made a new merge request: #2692

**Pull request closed without merging**
