### PR TITLE
Added support to BTC >= 0.16

### PR DESCRIPTION
**Pull request by lubuzzo**
As asked at [**Chaincoin**'s Discord](https://discord.gg/NabdcJ7) and here #2699 

I updated the code to be compatible with all current versions of BTC (<=0.15 and >= 0.16)

### CODE REVIEW

**Comment by lubuzzo** [comment]
@TheSerapher, done.

**Comment by TheSerapher** [comment]
Quick search shows some more places where `getinfo` is called, please go through those places (not the `bitcoin.class.php` though) and replace those as well.

**Comment by lubuzzo** [comment]
In my tests, `$bitcoin->getinfo() `is calling the method from the `bitcoin.class.php`, **so is fine**.

You can test opening the admin's dashboard, or admin's wallet. All the stats, that was previous got from getinfo (bitcoin rpc method, not bitcoin.class) is working at <= 0.15 and >= 0.15.

**Comment by TheSerapher** [comment]
You are the man, lets merge this bad boy :-)

**Comment by lubuzzo** [comment]
As the great Andrew Martin used to say, "One is glad to be of service".

Soon we'll change the CHC's testnet pool system to php-mpos, that is based on the newest version of BTC. So, if we found any trouble I'll be back here and solve.

And thanks, @TheSerapher <3

**Comment by TheSerapher** [comment]
Excellent, thanks again @lubuzzo :)

**Pull request merged**
